# Generated by Django 4.1.3 on 2022-11-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region_large', models.CharField(max_length=20)),
                ('latitude', models.IntegerField()),
                ('longtitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('latitude', models.IntegerField()),
                ('longtitude', models.IntegerField()),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.placetype', verbose_name='place_type')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.region', verbose_name='region')),
            ],
        ),
    ]
