# Generated by Django 4.1.3 on 2022-11-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default='', null=True)),
                ('latitude', models.IntegerField()),
                ('longtitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_small', models.CharField(max_length=20)),
                ('region_large', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TagToPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.place', verbose_name='place_id')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.placetag', verbose_name='tag_id')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField(blank=True, null=True)),
                ('index', models.IntegerField(default=1, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.place', verbose_name='place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.region', verbose_name='region'),
        ),
    ]
