# Generated by Django 4.1.3 on 2022-11-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_type',
        ),
        migrations.DeleteModel(
            name='PlaceType',
        ),
    ]
