# Generated by Django 4.1.3 on 2022-11-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_small',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
