# Generated by Django 4.1.3 on 2022-11-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
