# Generated by Django 4.1.3 on 2022-11-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_place_name_alter_region_region_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.TextField(default='', null=True),
        ),
    ]
