# Generated by Django 4.1.3 on 2022-11-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_alter_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeType',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('CAFE', 'CAFE'), ('SPOT', 'SPOT')], default='FOOD', max_length=10),
        ),
    ]
