# Generated by Django 4.1.3 on 2022-11-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_place_placetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
    ]
