# Generated by Django 4.1.3 on 2022-11-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
